// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBps4ZKy90FvsIKxDUu-N8zRh3hJFe-0hc',
    appId: '1:1059478759582:web:3e52934fc2d3d653c0f38f',
    messagingSenderId: '1059478759582',
    projectId: 'jokko-agro-mobile',
    authDomain: 'jokko-agro-mobile.firebaseapp.com',
    storageBucket: 'jokko-agro-mobile.firebasestorage.app',
    measurementId: 'G-HN32WG1FQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRBTsVHvZjxGW2y0xOzTJSsS8AotSDde0',
    appId: '1:1059478759582:android:8a9b4ee06dd04980c0f38f',
    messagingSenderId: '1059478759582',
    projectId: 'jokko-agro-mobile',
    storageBucket: 'jokko-agro-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7FoVCJGDCi6Ysy8CS8XXfNKezcak7kLk',
    appId: '1:1059478759582:ios:76051f87822361cdc0f38f',
    messagingSenderId: '1059478759582',
    projectId: 'jokko-agro-mobile',
    storageBucket: 'jokko-agro-mobile.firebasestorage.app',
    iosClientId: '1059478759582-nql4ribo98uhqna40uicvvue0343fmhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.jokkoAgroMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7FoVCJGDCi6Ysy8CS8XXfNKezcak7kLk',
    appId: '1:1059478759582:ios:76051f87822361cdc0f38f',
    messagingSenderId: '1059478759582',
    projectId: 'jokko-agro-mobile',
    storageBucket: 'jokko-agro-mobile.firebasestorage.app',
    iosClientId: '1059478759582-nql4ribo98uhqna40uicvvue0343fmhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.jokkoAgroMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBps4ZKy90FvsIKxDUu-N8zRh3hJFe-0hc',
    appId: '1:1059478759582:web:c8908e5545c77e91c0f38f',
    messagingSenderId: '1059478759582',
    projectId: 'jokko-agro-mobile',
    authDomain: 'jokko-agro-mobile.firebaseapp.com',
    storageBucket: 'jokko-agro-mobile.firebasestorage.app',
    measurementId: 'G-C2ZNM5JQ3F',
  );
}
